### ISSUE TITLE
Efi

### ISSUE THREAD

**Issue by murat075** [RafiZz/msi-gl65-9sc-hackintosh#1]
If there is a new efi file, can you update it?

**Comment by RafiZz** [comment]
#d43c90949e18c04b3974f78d1a8f851da8db93c4

**Comment by rbikbov** [comment]
The repository has been updated. Perhaps I missed some problems, but the current state of the repository makes it work comfortably in the big Sur 11.6.

**Comment by siddhantapoudel** [comment]
Hello, Does the wifi and Bluetooth works? Thanks

**Comment by rbikbov** [comment]
Hello.
Before that I have bcm943602cs which worked natively.
Yesterday I replaced it with intel9560ngw (it was in the laptop when I bought it) and made [changes](https://github.com/RafiZz/msi-gl65-9sc-hackintosh/commit/2f8c3f82a99aef30cfd4049dabf0d1d8f7fdc78c).
Everything works, but sometimes I can't connect to the network the first time. It may have been a problem with my router, I'm not sure.
