### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by guptaishan1** [RafiZz/msi-gl65-9sc-hackintosh#2]
it is running every thing quite natively but its very slow can you tell me how to use it for mojave.

**Comment by rbikbov** [comment]
Hi.
If I understand correctly, then you have a problem with igpu acceleration.
This can be understood if you have 7mb in the graphics line as in the ![screenshot](https://user-images.githubusercontent.com/19607880/134308047-b136a8d9-c3ba-4eec-a8a6-1060a65987bd.png)
If so: 
1) and you have the same processor (i5-9300h) but you are running mojave you can try to downgrade SMBIOS from 16.3 to 15.1 for example
2) or try to edit settings in [this dict](https://github.com/RafiZz/msi-gl65-9sc-hackintosh/blob/master/EFI/OC/config.plist#L388) ([configuration guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html))

This is my [Geekbench 5 result](https://browser.geekbench.com/v5/cpu/9992974)

Unfortunately I have not followed OpenCore changes and cannot tell what changes are required for mojave running

**Comment by guptaishan1** [comment]
Thank you very much for reply I'll try it
Peace

**Comment by guptaishan1** [comment]
Hey i just had one doubt is it in workable condition on your laptop or is
it working as fast as mac p.s sorry for my bad english

**Comment by ishangupta-1510** [comment]
I solved the issue it is working great now thank you so much
